- app/assets/stylesheets/components/alerts.scss
- app/views/layouts/application.html.erb
- app/views/layouts/auth.html.erb
- app/views/layouts/error.html.erb
- app/views/layouts/setup.html.erb
- app/views/shared/_flash_messages.html.erb
- config/locales/devise.en.yml
- db/schema.rb
- styling up the sign in page a little
- moved noticed to top of page, not fixed
- removed devise unauthenticated message
> Sign in page

- app/controllers/team_controller.rb
- app/models/team_user.rb
- app/views/team/show.html.erb
- config/routes.rb
- update a users role in a team
- remove a user from a team
> Admin update user

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/alerts.scss
- app/assets/stylesheets/components/grids.scss
- app/assets/stylesheets/components/lists.scss
- app/assets/stylesheets/components/type.scss
- app/assets/stylesheets/styles/auth.scss
- app/assets/stylesheets/styles/confirm-dialog.scss
- app/assets/stylesheets/styles/files.scss
- app/assets/stylesheets/styles/search.scss
- app/assets/stylesheets/styles/setup.scss
- app/assets/stylesheets/styles/tasks.scss
> added autoprefixer and removed reference to old webkit etc css

- app/models/concerns/searchable.rb
- app/models/project.rb
- app/models/story.rb
- app/models/task.rb
- when a project is archived/restored, make sure to reindex its stories also
- when a story is archived/restored, make sure to reindex all tasks, comments and attachments on it
> Search indexing

- app/controllers/search_controller.rb
- app/models/search_document.rb
only search projects within a team the user is part of
> use project ids when searching

- app/assets/javascripts/features/auto-search.js
- app/assets/javascripts/features/mousetrap.js
- app/views/layouts/application.html.erb
only able to search when within a team page.
scroll to the top of the results every time a new search is performed
> Search tweaks

- app/assets/stylesheets/components/dropdown.scss
- app/assets/stylesheets/components/search-sidebar.scss
- app/assets/stylesheets/styles/header.scss
- app/views/shared/_signed_in_menu.html.erb
Make the header take up less space
> Compress header

- app/assets/javascripts/features/header_shadow.js
- app/assets/stylesheets/components/containers.scss
- app/assets/stylesheets/components/search-sidebar.scss
- app/assets/stylesheets/styles/header.scss
fix the header to the top of the page, and add a shadow as you scroll down
> fixed header

- app/assets/javascripts/features/tasks.js
- app/assets/javascripts/templates/tasks/task.jst.ejs
- app/assets/stylesheets/components/buttons.scss
- app/assets/stylesheets/styles/tasks.scss
double click on a task to bring up the edit form
positioning fix on the alert box to drop below the fixed header
> Dblclick tasks

- app/assets/javascripts/features/notifications.js
- app/assets/javascripts/templates/notifications/comment_created.jst.ejs
- app/assets/javascripts/templates/notifications/comment_mentioned.jst.ejs
- app/assets/javascripts/templates/notifications/no_notifications.jst.ejs
- app/assets/javascripts/templates/notifications/project_created.jst.ejs
- app/assets/javascripts/templates/notifications/story_created.jst.ejs
- app/assets/javascripts/templates/notifications/story_mentioned.jst.ejs
- app/assets/javascripts/templates/notifications/task_assigned.jst.ejs
- app/assets/javascripts/templates/notifications/task_completed.jst.ejs
- app/assets/javascripts/templates/notifications/task_created.jst.ejs
- app/assets/javascripts/templates/notifications/task_mentioned.jst.ejs
- app/assets/stylesheets/components/alerts.scss
- app/assets/stylesheets/components/notifications.scss
- app/controllers/notifications_controller.rb
- app/models/notification.rb
- app/serializers/notification_serializer.rb
- config/routes.rb
show at least 10 notifications in the dropdown at all times, including all unseen
> Notifications

- app/assets/javascripts/features/tasks.js
- app/assets/javascripts/templates/tasks/container.jst.ejs
- app/assets/javascripts/templates/tasks/task.jst.ejs
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/buttons.scss
- app/assets/stylesheets/components/datepicker.scss
- app/assets/stylesheets/styles/tasks.scss
- app/controllers/tasks_controller.rb
- app/models/project.rb
- app/serializers/task_serializer.rb
- app/views/stories/show.html.erb
- config/routes.rb
- db/migrate/20151014104537_add_due_at_to_tasks.rb
- db/structure.sql
- schedule a task to a date
- assign user and set due date when creating
- fix the show all completed button
- added a delete all completed tasks button
> Scheduled tasks

- app/assets/javascripts/features/search.js
- app/assets/javascripts/features/tasks.js
- app/assets/javascripts/templates/notifications/comment_created.jst.ejs
- app/assets/javascripts/templates/notifications/comment_mentioned.jst.ejs
- app/assets/javascripts/templates/notifications/project_created.jst.ejs
- app/assets/javascripts/templates/notifications/story_created.jst.ejs
- app/assets/javascripts/templates/notifications/story_mentioned.jst.ejs
- app/assets/javascripts/templates/notifications/task_assigned.jst.ejs
- app/assets/javascripts/templates/notifications/task_completed.jst.ejs
- app/assets/javascripts/templates/notifications/task_created.jst.ejs
- app/assets/javascripts/templates/notifications/task_mentioned.jst.ejs
- app/serializers/notification_serializer.rb
- app/views/notifications/_deleted_item.html.erb
- app/views/notifications/index.html.erb
- make warmdown wait for tasks to be added.
- check for hash change before adding warmdown.
- quick fix for notifications when notifiable/project/story has been deleted
> Warmdown fix

- app/controllers/api/v1/attachments_controller.rb
- app/controllers/api/v1/comments_controller.rb
- app/controllers/api/v1/notifications_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/search_controller.rb
- app/controllers/api/v1/stories_controller.rb
- app/controllers/api/v1/tasks_controller.rb
- app/controllers/api/v1/team_invites_controller.rb
- app/controllers/api/v1/user_controller.rb
- app/serializers/comment_serializer.rb
- app/serializers/current_user_serializer.rb
- app/serializers/project_serializer.rb
- app/serializers/story_serializer.rb
- app/serializers/task_serializer.rb
- app/serializers/user_serializer.rb
- config/initializers/active_model_serializers.rb
- config/routes.rb
- spec/api/v1/attachments_controller_spec.rb
- spec/api/v1/comments_controller_spec.rb
- spec/api/v1/notifications_controller_spec.rb
- spec/api/v1/projects_controller_spec.rb
- spec/api/v1/search_controller_spec.rb
- spec/api/v1/stories_controller_spec.rb
- spec/api/v1/tasks_controller_spec.rb
- spec/api/v1/team_invites_controller_spec.rb
- spec/api/v1/user_controller_spec.rb
APIs for:
- User
- Stories
- Tasks
- Comments
Also stubbed API controllers for most of the things we’ll need to write
> Other api endpoints

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/attachments_controller.rb
- app/controllers/api/v1/auth_controller.rb
- app/controllers/api/v1/comments_controller.rb
- app/controllers/api/v1/projects_controller.rb
- app/controllers/api/v1/stories_controller.rb
- app/controllers/api/v1/tasks_controller.rb
- app/controllers/api/v1/user_controller.rb
- config/initializers/apipie.rb
- config/routes.rb
> Api documentation

- app/controllers/api/v1/comments_controller.rb
- app/serializers/task_serializer.rb
- config/routes.rb
- spec/api/v1/comments_controller_spec.rb
- spec/features/file_browser_spec.rb
- spec/features/first_user_setup_spec.rb
- spec/features/inviting_team_members_spec.rb
- spec/features/project_spec.rb
- spec/features/story_spec.rb
- Make comments a root api resource
- Disable feature specs for old UI
> Flatten comments api endpoints

- app/assets/javascripts/controllers/story_controller.js
- app/assets/javascripts/directives/task_item.js
- app/assets/javascripts/services/task.js
- app/assets/javascripts/templates/directives/task_item.jst.ejs
- app/assets/javascripts/templates/stories/show.jst.ejs
- app/assets/stylesheets/styles/tasks.scss
- app/controllers/api/v1/stories_controller.rb
- app/models/project.rb
- app/serializers/story_serializer.rb
- app/serializers/task_serializer.rb
> Angular tasks

- app/assets/javascripts/controllers/story_controller.js
- app/assets/javascripts/services/stories_repository.js
- app/assets/javascripts/templates/directives/user_avatar.jst.ejs
- app/assets/javascripts/templates/stories/show.jst.ejs
- app/controllers/api/v1/stories_controller.rb
- config/initializers/time_as_json.rb
- config/routes.rb
- spec/api/v1/stories_controller_spec.rb
- API timestamps ISO8601
- Show collaborators on story view
- Use ng-src for user avatars
> Misc ng gear

- app/assets/javascripts/controllers/story_controller.js
- app/assets/javascripts/directives/task_item.js
- app/assets/javascripts/services/tasks_repository.js
- app/assets/javascripts/templates/stories/show.jst.ejs
- app/assets/stylesheets/styles/tasks.scss
- hide completed tasks by default
- only apply faded style to tasks completed inline
- show/hide the "show completed tasks" link if there are completed tasks
- delete all completed tasks link
> Angular completed tasks

- app/assets/stylesheets/styles/setup.scss
- app/controllers/setup/single_site_controller.rb
- app/views/layouts/setup.html.erb
- app/views/setup/single_site/invalid_aws_credentials.html.erb
- fixes styling issues on setup
- adds a check to ensure s3 credentials have been setup correctly
> Setup styles

- app/assets/javascripts/templates/directives/notification_items/comment_created.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/comment_mentioned.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/story_created.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/story_mentioned.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/task_assigned.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/task_completed.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/task_created.jst.ejs
- app/assets/javascripts/templates/directives/notification_items/task_mentioned.jst.ejs
- app/assets/stylesheets/components/notifications.scss
- app/serializers/notification_serializer.rb
check stories and projects etc. exist before setting the link_to in the notification serializer.
fix the link to story type from the notification templates
> Notifications bug fix
